name: madewithloveforlife
favicon: null
layout_spectrum: 0.23419
typography_spectrum: 0.97305
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5054914578795433
  lightness: 0.818135769572109
  saturation: 0.8394345773849636
  rhythmicContrast: 0.1647129247430712
purpose: []
